import type { Metadata } from "next";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";

export const metadata: Metadata = {
  title: "About OpenContract",
  description:
    "OpenContract makes public procurement easier to trace, understand and independently verify. About our methodology, limitations, and principles.",
};

export default function AboutPage() {
  return (
    <>
      <SiteHeader />
      <main>
        <div className="border-b border-border bg-surface">
          <div className="container-narrow py-10">
            <h1 className="text-display text-text-primary mb-3">
              About OpenContract
            </h1>
            <p className="text-body-lg text-text-secondary">
              Public money should leave a public trail.
            </p>
          </div>
        </div>

        <div className="container-narrow py-12 space-y-12">

          {/* What is OpenContract */}
          <section>
            <h2 className="text-heading-lg text-text-primary mb-4">
              What is OpenContract?
            </h2>
            <div className="prose-like space-y-4 text-body text-text-secondary leading-relaxed">
              <p>
                OpenContract is a public procurement transparency and verification
                platform. It makes it easier for citizens, journalists, auditors,
                and researchers to trace, understand, and independently verify
                public procurement records — from tender publication to contract
                completion.
              </p>
              <p>
                The platform records procurement lifecycle events against a structured
                data model and anchors key events to an EVM blockchain. This creates
                a tamper-evident public record that can be independently verified
                without relying on the OpenContract platform itself.
              </p>
            </div>
          </section>

          <div className="section-divider" />

          {/* What it is not */}
          <section>
            <h2 className="text-heading-lg text-text-primary mb-4">
              What OpenContract is not
            </h2>
            <div className="space-y-4 text-body text-text-secondary leading-relaxed">
              <p>
                OpenContract is not a corruption detection tool. It does not make
                findings of wrongdoing. It does not claim that signals or data
                points indicate illegal activity.
              </p>
              <p>
                Blockchain anchoring confirms that a record was registered and
                has not changed since registration. It does not verify that the
                contents of the record are truthful, accurate, or complete.
              </p>
              <p>
                Integrity signals are generated by deterministic rules applied
                to procurement data. A signal for a "single bidder" does not
                mean a procurement was improper — it means the data pattern
                matches a condition that may warrant closer review.
              </p>
            </div>
          </section>

          <div className="section-divider" />

          {/* Methodology */}
          <section>
            <h2 className="text-heading-lg text-text-primary mb-4">
              Methodology
            </h2>

            <h3 className="text-heading-sm text-text-primary mb-2">
              Data model
            </h3>
            <p className="text-body text-text-secondary mb-6 leading-relaxed">
              Procurement records follow the{" "}
              <a
                href="https://standard.open-contracting.org"
                className="text-[hsl(var(--status-info))] hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Open Contracting Data Standard (OCDS)
              </a>
              . Each procurement has a unique Open Contracting Identifier (OCID).
              The lifecycle covers planning, tendering, bid submission, evaluation,
              award, contract, implementation (payments, milestones), inspection,
              and completion.
            </p>

            <h3 className="text-heading-sm text-text-primary mb-2">
              Document registration
            </h3>
            <p className="text-body text-text-secondary mb-6 leading-relaxed">
              Documents are registered by computing a SHA-256 cryptographic hash
              of the file content. This hash — not the file itself — is stored
              in OpenContract and optionally anchored to a blockchain. Verification
              works by computing the same hash of any file and comparing it against
              registered hashes.
            </p>

            <h3 className="text-heading-sm text-text-primary mb-2">
              Blockchain anchoring
            </h3>
            <p className="text-body text-text-secondary leading-relaxed">
              Key events (procurement published, award published, contract
              created, contract amended, payment recorded) are anchored to the
              Base Sepolia testnet by submitting a transaction containing the
              SHA-256 hash of the canonical event data. The transaction hash
              provides a publicly verifiable, time-stamped record of when the
              event was registered.
            </p>
          </section>

          <div className="section-divider" />

          {/* Limitations */}
          <section>
            <h2 className="text-heading-lg text-text-primary mb-4">
              Known limitations
            </h2>
            <ul className="space-y-3 text-body text-text-secondary">
              {[
                "This is a demonstration environment. All data is fictional unless explicitly stated.",
                "Blockchain anchoring is on an EVM testnet (Base Sepolia), not Ethereum mainnet. Testnet data may be reset.",
                "Document hashing does not verify that the document content is truthful.",
                "Integrity signals are based only on data available in the platform.",
                "OpenContract cannot verify that all relevant procurement processes have been registered.",
                "The AI procurement analyst answers using application data. It may make errors. Always verify claims against the underlying records.",
              ].map((limitation) => (
                <li key={limitation} className="flex items-start gap-2">
                  <span className="mt-2 h-1.5 w-1.5 rounded-full bg-text-muted flex-shrink-0" aria-hidden />
                  {limitation}
                </li>
              ))}
            </ul>
          </section>

          <div className="section-divider" />

          {/* Demo environment */}
          <section>
            <div className="demo-banner mb-4 inline-flex">DEMO DATA</div>
            <h2 className="text-heading-lg text-text-primary mb-4">
              Demo environment
            </h2>
            <p className="text-body text-text-secondary leading-relaxed">
              All procurement records shown in this environment are fictional
              and created for demonstration purposes only. Any resemblance to
              real organizations, contractors, or procurement processes is
              unintended. The demonstration data is seeded to illustrate all
              features of the platform including document verification, timeline
              display, financial summaries, and integrity signals.
            </p>
          </section>

        </div>
      </main>
      <SiteFooter />
    </>
  );
}
